name: Build and Release

on:
  push:
    branches:
      - root

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7.2

    - name: Build and Package
      run: |
        dotnet build --configuration Release
        dotnet pack --configuration Release --output .

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "0"
        release_name: Latest Build
        draft: false
        prerelease: false
        assets: '*.zip'
