name: Build and Release

on:
  push:
    branches:
      - root

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Build and Package
      run: |
        msbuild.exe Argus.sln /p:platform="x64" /p:configuration="Win"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ env.PUBLIC_BUILD }}"
        release_name: Latest Build
        draft: false
        prerelease: false
        assets: '${{ env.Win }}/bin/Debug/*.zip'
